spring:
   application:
       name: xhq-interface
server:
  port: 3001

logging:
   config: classpath:log4j2.xml
##feign配置
feign:
  hystrix:
    enabled: true
  xhq-service:
    name: xhq-service
    url: http://localhost:2001/
##熔断配置
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 1000